import {REACT_APP_NYT_URL, REACT_APP_NYT_API_KEY, REACT_APP_GOOG_URL, REACT_APP_GOOG_API_KEY} from "@env";

export default {
    REACT_APP_NYT_URL, REACT_APP_NYT_API_KEY, REACT_APP_GOOG_URL, REACT_APP_GOOG_API_KEY
};