import {REACT_APP_NYT_URL, REACT_APP_NYT_API_KEY, REACT_APP_GOOG_URL, REACT_APP_GOOG_API_KEY, REACT_APP_NYT_CATEGORY, REACT_APP_NYT_CATEGORY_NAMES} from "@env";

export default {
    REACT_APP_NYT_URL, REACT_APP_NYT_API_KEY, REACT_APP_GOOG_URL, REACT_APP_GOOG_API_KEY, REACT_APP_NYT_CATEGORY, REACT_APP_NYT_CATEGORY_NAMES
};
